// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUuaZfAchcyv6dSm1CsAGpfZrFYAXXWq8',
    appId: '1:971978952726:web:882ee3d2b8a3dbe9b6a537',
    messagingSenderId: '971978952726',
    projectId: 'school-proj-c3bf0',
    authDomain: 'school-proj-c3bf0.firebaseapp.com',
    storageBucket: 'school-proj-c3bf0.firebasestorage.app',
    measurementId: 'G-F8V4F0VEYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdImEAQQQVgZE0aitFa9unlRhPgHJlWo8',
    appId: '1:971978952726:android:c0f2de4845a300b8b6a537',
    messagingSenderId: '971978952726',
    projectId: 'school-proj-c3bf0',
    storageBucket: 'school-proj-c3bf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhBA-ktBvnAfd1EZsriW6CnMpDkp2goEk',
    appId: '1:971978952726:ios:3fa6f7c5b2ec783fb6a537',
    messagingSenderId: '971978952726',
    projectId: 'school-proj-c3bf0',
    storageBucket: 'school-proj-c3bf0.firebasestorage.app',
    iosBundleId: 'com.example.basicApp',
  );
}
